[package]
name = "my_guessing_game"
version = "0.1.1"
edition = "2021"
authors = ["heropoo <aiyouyou1000@163.com>"]
description = "The guessing game from the Rust book"
license = "MIT"
repository = "https://github.com/heropoo/guessing_game.git"


[dependencies]
rand = "0.8.5"
